# Generated by Django 3.0.7 on 2020-06-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAlumno', models.CharField(max_length=75)),
                ('apellidoAlumno', models.CharField(max_length=75)),
                ('direccionAlumno', models.CharField(max_length=75)),
                ('telefonoAlumno', models.CharField(max_length=20)),
                ('correoAlumno', models.EmailField(max_length=100)),
                ('encargadoAlumno', models.CharField(max_length=75)),
                ('telefonoEncargado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=5)),
            ],
        ),
    ]
